global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:9090"]

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-service:9090"]

  - job_name: "music-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["music-service:9090"]

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:9090"]